Improved force printout in force matching. Allowed duplicate parameter ID. Fitting of second order condensed phase properties.
git-svn-id: https://simtk.org/svn/forcebalance@228 e93b7d5b-8bb4-0410-82c6-a20ae092c748

diff --git a/bin/ForceBalance b/bin/ForceBalance
--- a/bin/ForceBalance
+++ b/bin/ForceBalance
@@ -68,12 +68,16 @@ fi
 # Standard error gets written to its own .err file
 # Text overwritten by carriage returns are not saved
 $program $input 2>$error | tee >(awk -F '\r' '{print $NF}' > $output)
+exitstat=$?
 nerr=`wc -l $error | awk '{print $1}'`
-if [ $nerr -ne 0 ] ; then
+errlines=`grep error $error 2> /dev/null | wc -l | awk '{print $1}'`
+if [ $errlines -ne 0 ] || [ $exitstat -ne 0 ] ; then
     tail -50 $error
     echo
     echo "$program may not have finished successfully, see error above or look in $error."
     echo "If error does not make sense, please contact me (Lee-Ping)."
+elif [ $nerr -ne 0 ] ; then
+    echo "Look in $error for more (possibly relevant) printout."
 else
     rm $error
 fi
